alcohol <- read.csv("~/Desktop/alcohol.csv")
alcohol$grade <- (alcohol$G1 *2 + alcohol$G2 *2 +alcohol$G3)
t1<-table(alcohol$goout)
t2<-table(alcohol$Walc)
barplot(t1, xlab="Go Out Metric",ylab="Number of Students", main="How Going Out Affects Grades",col=colors,border="black")
barplot(t2, xlab="Alcohol Consumption",ylab="Number of Students", main="Walc vs Grade",col=colors,border="black")
boxplot(grade~goout,data=alcohol,xlab="Go Out Metric",ylab="Grade", main="How Going Out Affects Grades",col=colors,border="black")
boxplot(grade~Walc,data=alcohol,xlab="Walc",ylab="Grade", main="Walc vs Grade",col=colors,border="black")

goout1<- subset(alcohol, goout=='1')
goout5<- subset(alcohol, goout=='5')
Walc1<- subset(alcohol, Walc=='1')
Walc5<- subset(alcohol, Walc=='5')

mean(goout1$grade)
mean(goout5$grade)
mean(Walc1$grade)
mean(Walc5$grade)

PermutationTestSecond::Permutation(alcohol, "goout", "grade",1500,"1", "5")
PermutationTestSecond::Permutation(alcohol, "Walc", "grade",1500,"1", "5")
